package(default_visibility = ["//visibility:public"])

java_library(
    name = "src",
    srcs = glob(["com/vgalloy/empire/**/*.java"]),
    deps = [
        #        "@artifact_repo//org_springframework_boot_spring_boot_starter_aop",
        #        "@org_springframework_boot_spring_boot_starter_aop//jar",
        "@artifact_repo//:compile",
    ],
)
