package(default_visibility = ["//visibility:public"])

java_library(
    name = "logger_aspect_it",
    srcs = ["LoggerAspectIT.java"],
    deps = [
        "//empire-common/src/main/java:src",
        #        "@org_springframework_boot_spring_boot_starter_test//jar",
        #        "@org_mockito_mockito_core//jar",
        "@artifact_repo_test//:compile",
    ],
)
