package(default_visibility = ["//visibility:public"])

java_test(
    name = "logger_aspect_it",
    srcs = ["LoggerAspectIT.java"],
    test_class = "com.vgalloy.empire.common.log.LoggerAspectIT",
    deps = [
        "//empire-common/src/main/java:src",
        "@artifact_repo_test//:compile",
    ],
)
